- name: Demo on Variables
  hosts: frontend

  hosts: backend
  connection: localhost
  
  vars:
    COURSE: DevOps
    TRAINER: Siva Kumar
    DURATION: 4MONTHS

  tasks:
    - debug:
        msg: "Iam learning {{ COURSE }} From {{ TRAINER }}, and duration is about {{ DURATION}}"
      