- name: Demo on Filters
  hosts: frontend
  vars:
    topics: Linux, Shell, Ansible, Terraform
    tagMap:
      name: ansible
      project: roboshop
      environment: dev
    full_name: AmaRenDer EnUgU
    ip_address: 44.222.143.9
    tagsList: [
        {
            "key" : "name",
            "value" : "ansible"
        },

        {
            "key" : "project",
            "value" : "roboshop"

        },

        {
            "key" : "environment",
            "value" : "dev"

        }

    ]

  tasks:
  - name: convert string to list 
    debug:
      msg: "Topics are: {{ topics | split(',')}}"
  
  - name: set default value 
    debug:
      msg: " Hi {{ GREETING | default('Good Morning')}}"

  - name: convert map to list 
    debug:
      msg: "{{ tagMap | dict2items }}"
  
  - name: convert list to map 
    debug:
      msg: "{{ tagsList | items2dict }}"

  - name: convert full_name to UPPER case
    debug:
      msg: "{{ full_name | upper }}"

  - name: convert full_name to lower case 
    debug:
      msg: "{{ full_name | lower }}"