- name: demo on shell vs command
  hosts: frontend
  tasks:
  - name: command test
    #command: cat /etc/passwd | grep root
    shell: cat /etc/passwd | grep root
    register: users_output

  - name: print output 
    debug:
      msg: " {{ users_output }}" 
 
  - name: list files 
    #command: ls -lrt > /tmp/files.txt
    shell: ls -l > /tmp/files.txt