[frontend]
 54.81.17.232

[backend]
 44.222.143.9

[local]
localhost

; [frontend:vars]
; COURSE="Ansible from Inventory.ini"
; TRAINER="SivaKumar from Invenotry.ini"
; DURATION="10 hrs from Invenotory.ini"
